import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-yellow-100 text-black`}
      >
        <div className="border-4 border-blue-500 p-4 text-center">
          ✅ Layout is active
        </div>

        <div className="min-h-[60vh]">{children}</div>

        <div className="border-t-4 border-red-500 p-4 text-center">
          🔽 Layout Footer Area
          <Footer />
        </div>
      </body>
    </html>
  );
}
